name: ci

on:
  push:

jobs:
  slither:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1
        id: buildx
        with:
            install: true
        
      - name: Build Mev-Geth
        id: container
        shell: bash
        run: cd scripts/ && bash build-flashbots.sh
