name: Hadolint

on:
  push:

jobs:
  hadolint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Lint Dockerfile
      uses: hadolint/hadolint-action@v2
      id: hadolint
      with:
       dockerfile: flashbots/Dockerfile
