name: Hadolint

on:
  push:

jobs:
  hadolint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Lint Dockerfile
      uses: hadolint/hadolint-action@v2.1.0
      with:
       dockerfile: Dockerfile
